baseURL = "https://sneas.github.io/blog"
languageCode = "en-us"
title = "A bit of insights on software design"
theme = "minimal"
publishDir = "dist"

[params]
    author = "Dmitry Snisarenko"
    description = "Personal blog theme powered by Hugo"
    githubUsername = "sneas"
    accent = "#0366d6"
    showBorder = false
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "atom-one-light"
    highlightLanguages = ["javascript", "typescript", "bash"]
    css = ["css/code.css"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.icon]]
    url = "https://github.com/sneas/"
    name = "github"
    weight = 1
