version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
        - save_cache:
            paths:
            - node_modules
            key: v1-dependencies-{{ checksum "package.json" }}
      - run: hugo
      - run: npm run deploy
