version: 2
jobs:
  publish:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/repo
    branches:
      only:
        - master
    steps:
      - checkout
      - run:
        name: "Pull Submodules"
        command: |
          git submodule init
          git submodule update --remote
      - run: hugo
      - run: sh ./push-gh-pages.sh
