version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/repo
    branches:
      only:
        - master
    steps:
      - checkout
      - run: hugo
      - run: sh .circleci/push-gh-pages.sh dist
